#!/bin/env python

""" A biopython script to convert phd (phred quality) files to fastq files \
     that can be used for read mapping to a reference genome. The phred files \
     to be used were generated by Consed from raw Sanger reads.

    """

import os

from Bio import SeqIO

INPUTDIR = "."

def process(directory):
    filelist = os.listdir(directory)
    for f in filelist:
        SeqIO.convert(f, "phd", f.replace(".phd.1",".fastq"), "fastq-sanger")

process(INPUTDIR)
